language: php
php:
  - '7.1'
  - '7.2'
addons:
  mariadb: "10.2"
env:
  global:
    - COVERAGE=true TEST_COMMAND="phpdbg -qrr vendor/bin/phpunit --coverage-clover coverage.xml"
matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: COVERAGE=false TEST_COMMAND="composer lint"
before_install :
  - phpenv config-rm xdebug.ini
install:
  - travis_retry composer install
before_script:
  - mysql -e 'CREATE DATABASE yiitest;'
script:
  - $TEST_COMMAND
after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
