name: Continous integration
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  cs:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - uses: ramsey/composer-install@v3
      - name: Test code style
        run: vendor/bin/ecs
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: yiitest
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=10
    strategy:
      matrix:
        php: ['8.4', '8.5']
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl, php-coveralls/php-coveralls
          coverage: pcov
      - uses: ramsey/composer-install@v3
      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done
      - name: Set up database
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: mysql -u root -h"127.0.0.1" -P"$PORT" yiitest < tests/data/mariadb.sql
      - name: Run tests
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: composer test -- --coverage-clover clover.xml --coverage-text
      - name: Push code coverage
        if: matrix.php == '8.1' && github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: $(composer global config bin-dir --absolute)/php-coveralls -x clover.xml --json_path=upload.json -v
  release:
    name: Automated release
    needs: [test, cs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts'
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p conventional-changelog-conventionalcommits
          -p semantic-release
          -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
